#!/usr/bin/env bash
#This script displays "To infinity and beyond" indefinitely
#between each iteration of the loop, there is a sleep 2

while true
do
    echo "To infinity and beyond"
    sleep 2
done
