#!/usr/bin/env bash
#This script displays "Best School" 9 times and displays Hi on a new line

i=1
while [ $i -le 9 ]
do
    echo "Best School"
    if [ $i -gt 8 ]
    then
	echo "Hi"
    fi
    ((i++))
done
